
import { Option } from "@/components/ui/multi-select";
import { SectionDefinition } from "@/components/template-request/types";

// Section definitions
export const SECTIONS: SectionDefinition[] = [
  { id: 'about', label: 'À propos', required: true, description: "Présentez-vous et partagez votre histoire" },
  { id: 'contact', label: 'Contact', required: true, description: "Vos informations de contact" },
  { id: 'services', label: 'Services', required: true, description: "Les services que vous proposez" },
  { id: 'skills', label: 'Compétences', required: false, description: "Vos compétences professionnelles" },
  { id: 'projects', label: 'Projets', required: false, description: "Vos projets et réalisations" },
  { id: 'testimonials', label: 'Témoignages', required: false, description: "Ce que disent vos clients" },
  { id: 'gallery', label: 'Galerie', required: false, description: "Vos photos et images" },
  { id: 'process', label: 'Processus de travail', required: false, description: "Comment vous travaillez" },
  { id: 'timeline', label: 'Parcours', required: false, description: "Votre parcours professionnel" },
  { id: 'notable_cases', label: 'Affaires notables', required: false, description: "Vos cas les plus remarquables" },
  { id: 'publications', label: 'Publications', required: false, description: "Vos articles et publications" },
  { id: 'portfolio', label: 'Portfolio', required: false, description: "Votre portfolio de travaux" },
  { id: 'certifications', label: 'Certifications', required: false, description: "Vos certifications professionnelles" },
  { id: 'education', label: 'Parcours académique', required: false, description: "Votre formation et éducation" },
];

// Enhanced skills list by sector with more options
export const SKILLS_BY_SECTOR: Record<string, Option[]> = {
  consultant: [
    { label: "Stratégie", value: "strategie" },
    { label: "Gestion de projet", value: "gestion_projet" },
    { label: "Coaching", value: "coaching" },
    { label: "Communication", value: "communication" },
    { label: "Leadership", value: "leadership" },
    { label: "Analyse financière", value: "analyse_financiere" },
    { label: "Business development", value: "business_development" },
    { label: "Marketing stratégique", value: "marketing_strategique" },
    { label: "Conduite du changement", value: "conduite_changement" },
    { label: "Analyse de données", value: "analyse_donnees" },
    { label: "Négociation", value: "negociation" },
    { label: "Gestion des risques", value: "gestion_risques" },
    { label: "Facilitation", value: "facilitation" },
    { label: "Résolution de problèmes", value: "resolution_problemes" },
    { label: "Audit", value: "audit" },
    { label: "Design thinking", value: "design_thinking" },
    { label: "Gestion de crise", value: "gestion_crise" },
    { label: "Planification stratégique", value: "planification_strategique" }
  ],
  medecin: [
    { label: "Diagnostic", value: "diagnostic" },
    { label: "Soins", value: "soins" },
    { label: "Pédiatrie", value: "pediatrie" },
    { label: "Chirurgie", value: "chirurgie" },
    { label: "Médecine préventive", value: "preventive" },
    { label: "Imagerie médicale", value: "imagerie" },
    { label: "Cardiologie", value: "cardiologie" },
    { label: "Neurologie", value: "neurologie" },
    { label: "Dermatologie", value: "dermatologie" },
    { label: "Ophtalmologie", value: "ophtalmologie" },
    { label: "Psychiatrie", value: "psychiatrie" },
    { label: "Orthopédie", value: "orthopedie" },
    { label: "Urgences", value: "urgences" },
    { label: "Médecine interne", value: "medecine_interne" },
    { label: "Gynécologie", value: "gynecologie" },
    { label: "Anesthésie", value: "anesthesie" },
    { label: "Gériatrie", value: "geriatrie" },
    { label: "Endocrinologie", value: "endocrinologie" }
  ],
  avocat: [
    { label: "Droit civil", value: "civil" },
    { label: "Plaidoirie", value: "plaidoirie" },
    { label: "Négociation", value: "negociation" },
    { label: "Conseil", value: "conseil" },
    { label: "Droit pénal", value: "penal" },
    { label: "Droit des affaires", value: "affaires" },
    { label: "Droit immobilier", value: "immobilier" },
    { label: "Droit de la famille", value: "famille" },
    { label: "Propriété intellectuelle", value: "propriete_intellectuelle" },
    { label: "Droit du travail", value: "travail" },
    { label: "Droit fiscal", value: "fiscal" },
    { label: "Droit international", value: "international" },
    { label: "Médiation", value: "mediation" },
    { label: "Arbitrage", value: "arbitrage" },
    { label: "Rédaction de contrats", value: "redaction_contrats" },
    { label: "Droit public", value: "public" },
    { label: "Droit bancaire", value: "bancaire" },
    { label: "Droit de l'environnement", value: "environnement" }
  ],
  photographe: [
    { label: "Portrait", value: "portrait" },
    { label: "Paysage", value: "paysage" },
    { label: "Studio", value: "studio" },
    { label: "Retouche", value: "retouche" },
    { label: "Événementiel", value: "evenementiel" },
    { label: "Mariage", value: "mariage" },
    { label: "Photo d'entreprise", value: "entreprise" },
    { label: "Architecture", value: "architecture" },
    { label: "Nature morte", value: "nature_morte" },
    { label: "Street photography", value: "street" },
    { label: "Photojournalisme", value: "photojournalisme" },
    { label: "Photographie culinaire", value: "culinaire" },
    { label: "Mode", value: "mode" },
    { label: "Boudoir", value: "boudoir" },
    { label: "Sport", value: "sport" },
    { label: "Astrophotographie", value: "astro" },
    { label: "Drone", value: "drone" },
    { label: "Photographie animalière", value: "animalier" }
  ],
  developpeur: [
    { label: "React", value: "react" },
    { label: "NodeJS", value: "nodejs" },
    { label: "TypeScript", value: "typescript" },
    { label: "DevOps", value: "devops" },
    { label: "Cloud", value: "cloud" },
    { label: "Python", value: "python" },
    { label: "Java", value: "java" },
    { label: "C#", value: "csharp" },
    { label: "PHP", value: "php" },
    { label: "Ruby", value: "ruby" },
    { label: "Mobile (iOS/Android)", value: "mobile" },
    { label: "Angular", value: "angular" },
    { label: "Vue.js", value: "vue" },
    { label: "AWS", value: "aws" },
    { label: "Azure", value: "azure" },
    { label: "Google Cloud", value: "gcp" },
    { label: "Docker", value: "docker" },
    { label: "Kubernetes", value: "kubernetes" },
    { label: "GraphQL", value: "graphql" },
    { label: "SQL", value: "sql" },
    { label: "NoSQL", value: "nosql" },
    { label: "Tests automatisés", value: "testing" },
    { label: "CI/CD", value: "cicd" }
  ],
  architecte: [
    { label: "CAO", value: "cao" },
    { label: "Gestion projet", value: "gestion-projet" },
    { label: "Aménagement", value: "amenagement" },
    { label: "Dessin", value: "dessin" },
    { label: "3D", value: "3d" },
    { label: "Architecture durable", value: "durable" },
    { label: "Maquettes", value: "maquettes" },
    { label: "Plans techniques", value: "plans" },
    { label: "Rénovation", value: "renovation" },
    { label: "Architecture intérieure", value: "interieur" },
    { label: "Urbanisme", value: "urbanisme" },
    { label: "BIM", value: "bim" },
    { label: "Réglementation", value: "reglementation" },
    { label: "Suivi de chantier", value: "chantier" },
    { label: "Conception bioclimatique", value: "bioclimatique" },
    { label: "Acoustique", value: "acoustique" },
    { label: "Coordination", value: "coordination" },
    { label: "Estimation de coûts", value: "couts" }
  ],
  professeur: [
    { label: "Pédagogie", value: "pedagogie" },
    { label: "Discours", value: "discours" },
    { label: "Coach scolaire", value: "coach-scolaire" },
    { label: "Sciences", value: "sciences" },
    { label: "Langues", value: "langues" },
    { label: "Mathématiques", value: "mathematiques" },
    { label: "Littérature", value: "litterature" },
    { label: "Histoire-Géographie", value: "histoire-geo" },
    { label: "Philosophie", value: "philosophie" },
    { label: "Économie", value: "economie" },
    { label: "Arts", value: "arts" },
    { label: "Éducation physique", value: "education-physique" },
    { label: "Évaluation", value: "evaluation" },
    { label: "Gestion de classe", value: "gestion-classe" },
    { label: "Édition de cours", value: "edition-cours" },
    { label: "Tutorat", value: "tutorat" },
    { label: "Enseignement numérique", value: "enseignement-numerique" },
    { label: "Méthodes actives", value: "methodes-actives" }
  ],
  cv: [
    { label: "Recherche", value: "recherche" },
    { label: "Présentation", value: "presentation" },
    { label: "Français", value: "francais" },
    { label: "Anglais", value: "anglais" },
    { label: "Organisation", value: "organisation" },
    { label: "Travail d'équipe", value: "travail-equipe" },
    { label: "Autonomie", value: "autonomie" },
    { label: "Adaptabilité", value: "adaptabilite" },
    { label: "Analyse", value: "analyse" },
    { label: "Communication orale", value: "comm-orale" },
    { label: "Communication écrite", value: "comm-ecrite" },
    { label: "Gestion du temps", value: "gestion-temps" },
    { label: "Résolution de problèmes", value: "resolution-problemes" },
    { label: "Créativité", value: "creativite" },
    { label: "Leadership", value: "leadership" },
    { label: "Esprit critique", value: "esprit-critique" },
    { label: "Esprit d'initiative", value: "initiative" },
    { label: "Capacité d'apprentissage", value: "apprentissage" }
  ],
  autoentrepreneur: [
    { label: "Gestion d'entreprise", value: "gestion-entreprise" },
    { label: "Marketing", value: "marketing" },
    { label: "Vente", value: "vente" },
    { label: "Service client", value: "service-client" },
    { label: "Comptabilité", value: "comptabilite" },
    { label: "Facturation", value: "facturation" },
    { label: "Réseaux sociaux", value: "reseaux-sociaux" },
    { label: "Prospection", value: "prospection" },
    { label: "Gestion de projet", value: "gestion-projet-ae" },
    { label: "Négociation", value: "negociation-ae" },
    { label: "Rédaction web", value: "redaction-web" },
    { label: "E-commerce", value: "e-commerce" },
    { label: "Stratégie de prix", value: "strategie-prix" },
    { label: "Gestion du temps", value: "gestion-temps-ae" },
    { label: "Relations clients", value: "relations-clients" },
    { label: "Stratégie digitale", value: "strategie-digitale" },
    { label: "SEO", value: "seo" },
    { label: "Juridique TPE", value: "juridique-tpe" }
  ]
};

// French city suggestions
export const CITY_SUGGESTIONS = [
  "Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", 
  "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne", "Toulon", "Le Havre", 
  "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne"
];
